### ISSUE TITLE
[RFC] 0.5 Sampler Design for Heterographs

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#1199]
## 🚀 Feature
We have finally settled down (in principle) the design of the long-awaited sampling on heterogeneous graphs, and we have started working on it.

This issue keeps track of the implementation progress.

**You're welcome to read the proposal publicly available on https://docs.google.com/document/d/1cVvbM_QtaIN0UsqrgB0FhlYti1PjXua2QbSAoMaE2ng/edit**

The document is not fixed and it is subject to changes: you're welcome to provide feedback on either the proposal itself or this issue thread.

## Task tracker

- [ ] C APIs
  - [ ] Neighbor sampling [@jermainewang ]
    - [x] sample_neighbors
    - [x] sample_neighbors_topk
    - [x] in_subgraph
    - [x] out_subgraph
    - [ ] sample_layerwise
  - [ ] Random walks
    - [x] random_walk [@BarclayII ]
    - [x] random_walk_with_restart [@BarclayII ]
    - [ ] node2vec_random_walk
  - [ ] Misc
    - [ ] `dgl::aten` refactor to cover float types as well (only necessary ones)
    - [x] create_graph_from_paths [@BarclayII ]
    - [x] compact_graphs [@BarclayII ]
    - [x] to_simple_graph [@BarclayII ]
    - [x] dgl.choice(prob_array, num_samples) (faster numpy.random.choice) [@yzh119, already done in #1142 , may a python interface is required? ]
    - [x] Graph.remove_edges() [@BarclayII ]
- [ ] Models (rewrite)
  - [ ] GCN [@jermainewang ]
  - [ ] GCN with Control Variate Sampling
  - [x] GraphSAGE (with distributed) [@jermainewang ]
  - [ ] GraphSAGE with Control Variate Sampling
  - [ ] PinSAGE (with distributed) [@BarclayII ]
  - [ ] GCMC [@jermainewang ]
  - [x] RGCN? [@jermainewang ]
  - [ ] GAT?
  - [ ] FastGCN?
  - [ ] DGI?
  - [ ] Adaptive Layerwise Sampling?

Related:
* Unification of DGLGraph, DGLHeteroGraph, SubGraph, BatchedGraph, etc.
* Shared memory storage

**Comment by BarclayII** [comment]
@yzh119 I'm thinking of putting the `dgl.choice` as `RandomEngine::ThreadLocal()->Choice(FloatArray unnormalized_prob)`
