### ISSUE TITLE
[Roadmap] v0.4.3 Release

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#1388]
We have scheduled a minor release v0.4.3 on **03/31/20** due to the increasing demands of nightly build and the separation of DGL-LifeSci and DGL-KE as standalone projects. The included features are:

- [x] Clean up DGL-KE codes and move them to a dedicated repository.
- [ ] Clean up DGL-LifeSci codes and move them to a dedicated repository.   (@mufeili )
  - [ ] Make DGL-LifeSci (previously named DGL-Chem) a standalone package.
  - [ ] Documentation migration.
  - [ ] Add CI.
  - [x] Add utilities for featurization and graph construction (PR #928 ).
  - [x] Add utilities for dataset splitting (PR #1117 )
  - [x] Add AttentiveFP for property prediction (PR #955 )
  - [x] Add PDBBind dataset and related featurization (PR #1117 )
  - [x] Add data loading utilities (PR #1117 )
  - [x] Add ACNN for protein-ligand binding affinity prediction (PR #1117 )
- [x] Official release of Tensorflow support. (@VoVAllen )
  - [x] DLPack support in Tensorflow mainline (https://github.com/tensorflow/tensorflow/pull/36862)
  - [x] Tensorflow backend in DGL (PR: #978 )
  - [x] Models, NN modules, examples. (RFC: #1131 )
  - [x] Profiling and performance measurement.
  - [x] Migrate dependency of tf-dlpack to the latest TF rc version.
- [x] More flexible sampler APIs and sampling on heterogeneous graph. See full tracker here #1199 #1209 , but only the items below will be included.
  - [x] Core random walk APIs #1209 
  - [x] Core sampler APIs #1251 
  - [x] GraphSAGE example with mini-batch training on multi-GPU #1274  #1333 
  - [x] RGCN-hetero example with mini-batch training #1337 
  - [x] HeteroGraphConv NN module #1385 @jermainewang 
- [x] Support pickling/unpickling DGLHeteroGraph #1299 
- [x] Support load and save DGLHeteroGraph #1295 
- [x] Merge DGLGraph, DGLSubGraph and BatchedDGLGraph #1216 
- [x] Deprecate the `multigraph` option in DGLGraph #1389 
- [x] Improve all NN modules so that they support bipartite graph @yzh119 #1392
