### ISSUE TITLE
[Release] v0.1 release checklist

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#183]
Bugfix
--------
- [x] Support inplace write for `recv`, `pull`, `push`, `send_and_recv`. **[Lingfan]** #221 
- Fix consecutive send, recv. **[minjie]** (fix in next patch)

API document
-------------------
- [x] DGLGraph (`graph.py`)
  - [x] Adding nodes and edges **[Quan]** #207 
  - [x] Querying graph structure **[Quan]** #207 
  - [x] Transforming graph / Subgraph (`subgraph.py`) **[Quan]** #207 
  - [x] Converting from/to other format **[Lingfan]** #245 
  - [x] Using node/edge features / NodeView / EdgeView / Initializer (`view.py`, `init.py`) [Lingfan] #245 
  - [x] Computing with DGLGraph **[minjie & murphy]**
- [x] UDF, NodeBatch, EdgeBatch **[murphy]**
- [x] BatchedDGLGraph **[murphy]** (`batched_graph.py`) #193 
- [x] Builtin function (`dgl.function`) **[Lingfan]** #245 
- [x] Graph traversal / Message propagation (`propagate.py`, `traversal.py`) **[Lingfan]** #245 
- [x] Data provider (`dgl.data`) **[murphy]** #212 

Tutorials
------------
- [x] DGMG (#204   #175 ) **[Murphy, Lingfan]**
- [x] RGCN (#206 #55 ) **[Lingfan]**
- [x] Transformer (drafted) **[Zihao & JJ]** (does not affect 0.1 release)
- [x] Linegraph (drafted) **[HQ, Gaiyu]** #210 
- [x] SSE **[Gaiyu, Da]**
~~- [ ] GAT~~

Other Docs
---------------
- [x] Installation **[minjie & Quan]** #223 
- [x] Github-io page **[Lingfan]**
- [x] FAQ
- [x] Contribution guide
- [x] Issue template #192 
- [x] PR template #192 
- [x] Discuss forum
~~- [ ] Doc Auto Build~~

Lint
-----
- `graph.py`
- `dgl.runtime`
- `frame.py`
- backend.pytorch
- backend.mxnet [Da]
- contrib [Da]
- data
- function
- nn
- others in root package

Notes:
* Lint check is lower priority.
