### ISSUE TITLE
[Roadmap] GNN models, modules and others

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#3849]
dgl.nn
- [x] Simplify RelGraphConv
- [x] NN module: HGTConv
- [x] LabelPropagation #4017
- [ ] GraphSizeNorm
- [x] SIGNDiffusion transform #3982 
- [ ] TopKPooling
- [ ] GENConv
- [x] GINEConv #3934 
- [ ] ARMAConv
- [ ] KGNNConv
- [x] PNAConv #3901 
- [ ] CorrectAndSmooth
- [ ] GraphNorm
- [x] GATv2Conv
- [ ] HypergraphConv
- [ ] SE3 Transformer
- [ ] Radial field network
- [ ] TFN
- [ ] SchNet
- [x] EGNN Conv #3901 
- [ ] MetaPath2Vec

Explainability modules:
- [x] GNNExplainer
- [ ] PGExplainer
- [ ] General solution for compatibility with Captum

Samplers
- [x] ClusterGCN
- [x] ShaDow
- [ ] FastGCN
- [x] GraphSAINT samplers/dataloaders (node, edge, random walk) #3879 
- [ ] HGT sampler
- [ ] LADIES sampler
- [ ] TGAT sampler
- [ ] SEAL sampler #4291 
- [ ] Causal Anonymous Walks

dgl.transforms
- [x] Randomly add/drop nodes/edges
- [x] Graph Diffusion Convolution
- [ ] Positional node encoding
    - [x] RandomWalkPE, LaplacianPE #3869 
- [x] Feature masking #3968
- [x] Row Feature Normalizer #3968  
- [x] Fast approximation of PPR  #3982 
- [ ] VirtualNode
- [x] #4372

Datasets
- [x] Yelp  #4099 
- [x] Flickr #4099 
- [x] WikiCS #4035 

Model examples
- [x] Large-Scale Representation Learning on Graphs via Bootstrapping #4077
- [ ] SEAL example to reproduce OGBL result #4291 
- [ ] GNNAutoScale
- [ ] SE3 Transformer
- [ ] OrbNet
- [ ] D-MPNN
- [ ] mtgnn
- [ ] gcnlstm
- [ ] Graph Matching Network
- [ ] GraphRNN: https://github.com/JiaxuanYou/graph-generation
- [ ] Graph2Seq work from #2931
- [ ] NGNN + GraphSAGE/GCN, NGNN + SEAL for OGBL #4328 

Graph embedding NN modules
- [x] #4368
- [x] #4369
- [ ] #4370

**Comment by mufeili** [comment]
1. How to prevent two contributors from working on the same item?
2. Any description of the general contribution process? E.g., open an issue first to discuss the design and to-do items

**Comment by jermainewang** [comment]
Just reply in the thread about which items you would like to contribute. Yes, we recommend open a dedicated discussion issue about the item and we will link it in the roadmap.

**Comment by Ziyang-Yu** [comment]
I am wondering if there is someone who already finished **TopKPooling**. I want to contribute to this item.

**Comment by mufeili** [comment]
@Ziyang-Yu Not to my knowledge. It will be great if you can contribute that!
