### ISSUE TITLE
[Roadmap] DGL-Go

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#3912]
DGL-Go is DGL's command line interface (CLI). See https://github.com/dmlc/dgl/tree/master/dglgo

- [ ] Add `dgl apply` command to apply a trained GNN model to a dataset.
- [ ] Add the training pipeline for graph prediction task and release:
  - [ ] 2 models (GIN w/ virtual node, PNA)
  - [ ] 2 datasets (ogbg-molhiv, ogbg-molpcba)
  - [ ] 4 off-the-shelf recipes
- [ ] **Customizability**
  - [ ] Support importing custom models to DGL-Go pipeline
  - [ ] Support importing custom datasets (beyond CSV datasets)
  - [ ] Support custom loggers (e.g., TensorboardLogger).
- [ ] Allow users to configure graph data transforms.
- [ ] Support loading pre-trained models for fine-tuning.
- [ ] GUI interface for `dgl configure`
