### ISSUE TITLE
List of missing support from MXNet in DGL project

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#435]
## 🚀 Feature

We use this issue as a list of required but currently missing features of MXNet. We also need to prioritize them.

- [x] [split](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L111) with sizes_of_sections
- [ ] [segment_sum](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L162) / max / mean / ...
- [ ] [unique](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L200) (@szha: requires apache/incubator-mxnet#12732, didn't find issue specific for this)
- [ ] [nonzero_1d](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L209)
- [ ] [sort](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L215) that returns both sorted array and argsort (@szha: topk has ret_type which needs to be added to sort)
- [x] [zerocopy_to/from_numpy](@szha: https://github.com/dmlc/dgl/blob/master/python/dgl/backend/mxnet/tensor.py#L234) (apache/incubator-mxnet#14244)

Performance related:
- [x] CustomOp (ends up with `autograd.Function`, and it works pretty well)

**Comment by zheng-da** [comment]
should we create an issue at mxnet repo?

**Comment by VoVAllen** [comment]
What's the difference between segment_sum and scatter_sum?

**Comment by jermainewang** [comment]
segment_sum assumes continuous index while scatter_sum not.

**Comment by jermainewang** [comment]
> should we create an issue at mxnet repo?

Is there an on-going issue in mxnet we could refer to?

**Comment by szha** [comment]
I added related issue from what I know. Please create the rest

**Comment by eric-haibin-lin** [comment]
we can create separate issues in mxnet with labels (sparse, numpy, etc) and use this issue to track the progress

**Comment by jermainewang** [comment]
That's a good idea. I could help create these issues in MXNet and maintain links to this issue if you want.

**Comment by zheng-da** [comment]
should we list all problems here and create issues in the mxnet repo for each category? i guess it's nice to have everything in one place.

**Comment by zheng-da** [comment]
Here is a list of other issues in MXNet:
- [ ] constructing a CSR matrix from the coo input is slow: https://github.com/apache/incubator-mxnet/issues/14311
- [ ] some of the MXNet operators in CPU are very slow. A typical example is concat.
- [ ] _backward_take in GPU is very slow.
- [ ] MXNet operators don't support int64.

**Comment by zheng-da** [comment]
actually, split with sizes_of_sections is supported in MXNet now. I forgot to update it in DGL.

**Comment by junrushao1994** [comment]
Do you guys really need zero-copy NDArray a from numpy? If so, I can try to implement.

**Comment by jermainewang** [comment]
@zheng-da I've updated the list. Removed sparse related requirements as DGL now handles all the sparse operations. Could you track the status again and update this thread?

**Comment by junrushao1994** [comment]
@jermainewang zero-copy from numpy has been implemented.

**Comment by zheng-da** [comment]
@junrushao1994 do we need to change anything to use zero-copy from numpy?

**Comment by junrushao1994** [comment]
@zheng-da Try [this](https://github.com/apache/incubator-mxnet/blob/e8a20fbb15fb1e8f8cb89c28ccdbc264b661fde6/tests/python/unittest/test_ndarray.py#L1686). Note that only non-strided arrays are supported

**Comment by zheng-da** [comment]
split and zero copy from NumPy is done.
https://github.com/dmlc/dgl/pull/660
