### ISSUE TITLE
[Roadmap] Example refactor

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#4371]
The goal is to make all important examples runnable and unify their code style.

- [x] Refactor GraphSAGE to be the golden standard #4186 
- [x] Refactor GAT #4240 
- [x] #4264 
- [x] Refactor GIN #4280 
- [x] Refactor RGCN #4327 
- [x] #4381
- [x] #4382
- [x] #4409 
- [x] #4410 
- [x] #4411

**Comment by jermainewang** [comment]
@chang-l @mufeili Please add tasks to this list.

**Comment by chang-l** [comment]
Add-ons:
- [ ] https://github.com/dmlc/dgl/issues/4409
- [ ] https://github.com/dmlc/dgl/issues/4410
- [ ] https://github.com/dmlc/dgl/issues/4411

**Comment by jermainewang** [comment]
@chang-l Updated the list with your items. Let me know if you have more updates.

**Comment by jermainewang** [comment]
Closed as this has been shipped in v1.0.
