### ISSUE TITLE
[Bug] CUDA stream synchronization issue between pytorch and DGL internal functions

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4436]
## CUDA stream support tracker

- [x] Make TensorAdaptor stream-aware. #4470 #4472
- [x] Clean the improper CUDA stream usage in the core library, including CUB and many hard-coded default stream (0 or nullptr). #4471 #4480
- [x] Add stream-related utilities to DGL, e.g., `.record_stream` for dgl.graph #4467, always use PyTorch's CUDA stream when it's available, etc. #4503

## 🐛 Bug

Update (08/19/2022):

When using a non-default stream for all torch operations (`torch.cuda.set_stream()`), there (DGL) lacks synchronizations in the core library (which always uses the default stream) if there is data-dependency.

-------------------------------

Under certain conditions like (1) using a non-default stream and  (2) with `torch.no_grad()`, a device assertion failure is occurred when calling `SpMM()` function.

After enabling `CUDA_LAUNCH_BLOCKING=1`, the assertion failure is disappeared.

I think this is caused by using different cuda streams for data-transferring and DGL internal functions, while lack of stream synchronizations.  Please see investigation section below.

## To Reproduce
Run the following python script:
```
import torch
import dgl
import torch.nn as nn
from dgl.nn.pytorch import RelGraphConv

class GraphConv(nn.Module):
    def __init__(self, in_channels, out_channels, num_edge_type=3):
        super(GraphConv, self).__init__()
        self.conv = RelGraphConv(in_channels, out_channels, num_edge_type)
        self.in_ch = in_channels
        self.out_ch = out_channels

    def forward(self, dgl_graph, e_type, input):
        res = self.conv(dgl_graph, input, e_type)
        return res

device = 0
# use a non-default stream
s = torch.cuda.Stream()
torch.cuda.set_stream(s)
# input_dim: 10, out_dim: 256,
model = GraphConv(10, 256).to(device)

# torch.no_grad() is necessary to reproduce the issue
with torch.no_grad():
    # graph: 10240 nodes, 409600 edges
    # generate src/dst node ids for 409600 edges
    src = torch.randint(10240, (409600,))
    dst = torch.randint(10240, (409600,))

    # generate dgl graph and find # of nodes
    dgl_graph = dgl.graph(data=(src, dst)).to(device)
    n_node = dgl_graph.num_nodes()

    # edge type id: 0, 1, 2 for all 409600 edges
    e_type = torch.randint(3, (409600,)).to(device)

    # run multiple forward passes to reveal the issue (critical!!!)
    node_feat = torch.rand(n_node, 10).to(device)
    for i in range(10):
        _ = model(dgl_graph, e_type, node_feat)
```

### Sample error message
```
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [373,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [373,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "entity.py", line 41, in <module>
    h = model(dgl_graph, e_type, node_feat)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "entity.py", line 14, in forward
    res = self.conv(dgl_graph, input, e_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dgl/nn/pytorch/conv/relgraphconv.py", line 167, in forward
    g.update_all(self.message, fn.sum('m', 'h'))
  File "/opt/conda/lib/python3.8/site-packages/dgl/heterograph.py", line 4895, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "/opt/conda/lib/python3.8/site-packages/dgl/core.py", line 365, in message_passing
    msgdata = invoke_edge_udf(g, ALL, g.canonical_etypes[0], mfunc, orig_eid=orig_eid)
  File "/opt/conda/lib/python3.8/site-packages/dgl/core.py", line 85, in invoke_edge_udf
    return func(ebatch)
  File "/opt/conda/lib/python3.8/site-packages/dgl/nn/pytorch/conv/relgraphconv.py", line 131, in message
    m = self.linear_r(edges.src['h'], edges.data['etype'], self.presorted)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dgl/nn/pytorch/linear.py", line 174, in forward
    return gather_mm(x, w, idx_b=x_type)
  File "/opt/conda/lib/python3.8/site-packages/dgl/ops/gather_mm.py", line 38, in gather_mm
    pos_r = torch.cat([pos_l[1:], torch.tensor([len(idx_b)], device=a.device)])
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.13
 - How you installed DGL (`conda`, `pip`, source): source
 - CUDA/cuDNN version (if applicable): 11.6
 - GPU models and configuration (e.g. V100): A5000

## Investigation
Several observations:
- Use default stream for pytorch avoids the crash
  For example, comment out `s = torch.cuda.Stream(); torch.cuda.set_stream(s)` in the above script.
- Apply sync after `torch.index_select` can fix this issue, as [here](https://github.com/dmlc/dgl/blob/d077d3719c88a460459323beda5462026b1ed9bb/python/dgl/ops/gather_mm.py#L40)
- Apply sync prior to `_CAPI_DGLKernelSpMM` also works, as [here](https://github.com/dmlc/dgl/blob/d077d3719c88a460459323beda5462026b1ed9bb/python/dgl/sparse.py#L228)

**Comment by chang-l** [comment]
Note that the above script uses a side stream for pytorch. In this sense, the zerocopy functions (through `torch.utils.dlpack`) is under a side stream, same as `torch.cuda.current_stream`.  Because DGL internally could use a different stream (default stream), I think we need to synchronize/wait the zero-copy stream before launching dgl internal functions, as the zero-copy data will be used there.

**Comment by yaox12** [comment]
I think DGL's core library doesn't fully support CUDA streams yet. For now, I suggest limiting the usage of alternative streams in data loading (not computing) only and carefully waiting/syncing with the main stream. @isratnisa @nv-dlasalle @BarclayII @jermainewang Please comment.

Regarding the above piece of code, though it doesn't throw an error when removing `torch.no_grad()`, the result could be incorrect because the computing kernel `SpMMCsrKernel` is called before the `indexSelected` kernel finished.

![image](https://user-images.githubusercontent.com/3831900/185536370-2483197a-fbcd-42ce-abfa-82eb4dfe6b5e.png)

![image](https://user-images.githubusercontent.com/3831900/185536454-be8bf7d1-f5e6-4b5e-9754-7ccae02cf054.png)

**Comment by chang-l** [comment]
Right, looking at the profiler, it smells like a severe bug... i.e., whenever pytorch launches on a **non-default** stream, DGL has no way to sync on that stream, and as a result, we will either get garbage results or just crashes. Notice the above simple example does not involve any dataloader (or using alternative stream for dataloading). 

I think we can either (1) enforce the same pytorch stream for DGL core library at beginning, or (2) apply stream sync at every necessary places (e.g., before launching MM-like kernels).

**Comment by nv-dlasalle** [comment]
Currently, DGL should only be used with the default stream (#2974).

Adding @BarclayII, @jermainewang, and @isratnisa as we've spent time discussing this issue before.

There are two issues here:
1. DLPack does not contain stream information, so when we pass tensors between DGL/PyTorch, we don't know which stream they were last operated on.
2. As a result of 1), DGL does not handle streams well in all operators. Many, but not all make calls thread_entry to get the stream information. I think to_block and compact_graphs need to be updated (this is my fault), and in most places we call `device->CopyDataFromTo()` we end up passing nullptr for the stream argument which executes it on the default stream.

We could potentially fix 1) by having all of our dgl.backend functions pass current stream information to DGL.

Fixing 2) should be done, but it would be a larger amount of work. I think we would also need some very intensive QA to ensure it works without issue.

I'm not sure what performance hit we would take by adding assertions to the pytorch backend to ensure they are called on the default stream, but it may help to improve the user experience in the near term. I'm also not aware if our documentation informs users that only the default stream works.

**Comment by yaox12** [comment]
> I'm also not aware if our documentation informs users that only the default stream works.

We definitely should do this.

**Comment by TristonC** [comment]
@nv-dlasalle  We should get it option 2 as you proposed done.

**Comment by jermainewang** [comment]
Reopen this since we found some of the related unit tests may fail unexpectedly. See error in https://github.com/dmlc/dgl/pull/4534#issuecomment-1255885055


Attached the log
```
=================================== FAILURES ===================================

______________________ test_record_stream_graph_negative _______________________

    @unittest.skipIf(F._default_context_str == 'cpu', reason="stream only runs on GPU.")
    def test_record_stream_graph_negative():
        cycles_per_ms = _get_cycles_per_ms()

        g = rand_graph(10, 20, device=F.cpu())
        x = torch.ones(g.num_nodes(), 10)
        result = OPS.copy_u_sum(g, x).to(F.ctx())

        stream = torch.cuda.Stream()
        results2 = torch.zeros_like(result)
        # Performs the computing in a background stream
        def perform_computing():
            with torch.cuda.stream(stream):
                g2 = g.to(F.ctx())
            torch.cuda.current_stream().wait_stream(stream)
            # omit record_stream will produce a wrong result
            # g2.record_stream(torch.cuda.current_stream())
            torch.cuda._sleep(int(50 * cycles_per_ms))  # delay the computing
            results2.copy_(OPS.copy_u_sum(g2, x))

        x = x.to(F.ctx())
        perform_computing()
        with torch.cuda.stream(stream):
            # g3 will reuse g2's memory block, resulting a wrong result
            g3 = rand_graph(10, 20, device=F.ctx())
        torch.cuda.current_stream().synchronize()
>       assert not torch.equal(result, results2)
E       AssertionError: assert not True
E        +  where True = <built-in method equal of type object at 0x7efd851e9e80>(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],\n        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],\n        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]], device='cuda:0'), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],\n        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],\n        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],\n        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],\n        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],\n        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]], device='cuda:0'))
E        +    where <built-in method equal of type object at 0x7efd851e9e80> = torch.equal

tests/pytorch/test_stream.py:158: AssertionError
```

**Comment by jermainewang** [comment]
@yaox12 @chang-l

**Comment by yaox12** [comment]
4/100 runs would fail even if I changed the sleep time to `int(500 * cycles_per_ms)`. 

Maybe we should just disable the `test_record_stream_graph_negative` since `test_record_stream_graph_positive` is enough.

**Comment by jermainewang** [comment]
Can you fix the random seed?

**Comment by chang-l** [comment]
This is a random crash and I also observed it in our internal CI today as well. 

I think this is an interesting problem and I did some study into this issue. BTW, thank you @jermainewang for providing the script here so that I can refer :) For the negative test, if the later allocated graph `g3` can completely override the first graph `g2`, then there is no doubt that the two results `result` and `results2` would be different and the unit test should always pass (it's highly unlikely that two random graphs with 10 nodes/20 edges are identical).

However, I found that `g3` and `g2` occupy different size of memory. The incremented memory size due to `g3` is much smaller than `g2`. This discrepancy is attributed to the function `copy_u_sum()`, i.e., calling `copy_u_sum(g, x)` would change the transferable size of graph (g) memory to device.  Here is a small demo script:

```
import torch
from dgl import rand_graph
import dgl.ops as OPS


g = rand_graph(10,20, device='cuda')
torch.cuda.empty_cache()
print('memory allocated (1st):', torch.cuda.memory_allocated())

gg = rand_graph(10, 20, device='cpu')
x = torch.ones(g.num_nodes(), 10)
OPS.copy_u_sum(gg, x)

gg2 = gg.to('cuda')
torch.cuda.empty_cache()
print('memory allocated (2nd == 2 x 1st ?):', torch.cuda.memory_allocated())
```
Output:
```
memory allocated (1st): 1024
memory allocated (2nd == 2 x 1st ?): 3584
```
By commenting out `OPS.copy_u_sum(gg, x)`, one can achieve the same memory allocation size, i.e., memory allocated (2nd)=2048

Therefore, coming back to our negative test, similarly, `g3` allocates/requests 1024 bytes in device, while `g2` needs to allocate/request 2560 bytes in device! (3584-1024=2560)  We can verify these two numbers, 1024 and 2560 for `g3` and `g2`, by memory footprint with `torch.cuda.memory_snapshot()`. So, even if `g3` and `g2` share the same device memory address, `g3` can only override part of mem. of  `g2`, which sometimes may not be sufficient to differ the two MM results.

As a result, I think if somehow equalize the two device memory allocations for`g3` and `g2`, we should be good. Here is my tentative fix: https://github.com/dmlc/dgl/commit/094cd7fc7f6fe3fa05ba82f1a43590147dbfd34d, where I additionally have an extra function call `OPS.copy_u_sum(g3, x)`, before we transfer `g3` to device memory. I have tested it >1000 times, and they all passed.

@yaox12, can you please verify it and also correct me if I misunderstood anything? Thanks. 

PS: In terms of why calling `OPS.copy_u_sum(g, x)` increased the transferable(to device) memory associated to graph `g`, I am not sure... Please feel free to comment @jermainewang @BarclayII @yaox12

**Comment by jermainewang** [comment]
Can we make the test result deterministic?

**Comment by yaox12** [comment]
@chang-l Thanks for your investigation, nice caught! The memory footprint was increased by calling `OPS.copy_u_sum(g, x)` because it will materialize other sparse formats. So a simple solution is to call `.create_formats()` for `g` and `g3` before transferring. I will send a PR to fix it.

**Comment by chang-l** [comment]
> Can we make the test result deterministic? e.g., fixing the random seed. Will that help?

@jermainewang 
I agree on making the test result deterministic by setting two different seeds. However, it wouldn't be enough to address this issue by just fixing the seeds (I tested and it still crashed with fixed seeds).
