### ISSUE TITLE
Kernel TODO list

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#641]
- [ ] NodeFlow update_all requires to build an adj matrix from edge list. We should build adj matrix from csr directly.
- [ ] NodeFlow should use bipartite graph index for each block.
- [ ] support mean reduction.
- [ ] MiniGun should use pull for computation to avoid atomic write. In addition, MiniGun should use blocking (2D partitioning) to increase data locality.

**Comment by jermainewang** [comment]
Could you put them in the roadmap thread? However, I feel that many of the minigun optimizations require more thorough research and understanding and would not be included in the next release. The bipartite graph problem should be fixed together with the heterograph support.
