### ISSUE TITLE
[GraphBolt][CUDA] Full GPU support for GraphBolt

### ISSUE THREAD

**Issue by mfbalin** [dmlc/dgl#6826]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Required components

- [x] Neighbor Sampling is being implemented without replacement and a homogenous case in #6770.
- [x] Extend Neighbor Sampling to heterogeneous cases in #6865.
- [x] Extend Neighbor Sampling to heterogeneous cases with different fanouts for each edge type in #6895.
- [x] #6918
- [ ] Extend Neighbor Sampling for the sample with replacement case.
- [ ] Extend NeighborSampling for temporal sampling.
- [x] `FusedCSCSamplingGraph::InSubgraph` for CUDA in #6830.
- [x] `IsIn` operator in #6829.
- [x] #6861.
- [x] Enable all tests for the GPU backend.
- [x] #6901
- [x] #6939 
- [x] #6955
- [x] #6962
- [x] #6978 

## Major optimizations

- [x] #6871
- [x] #6954 
- [x] #6983 and #7039
- [ ] #6910
- [ ] #7143
- [x] #7173
- [ ] #7272
- [x] #7174
- [ ] #7273

## Miscellaneous

- [ ] #6909
- [ ] #6981 
- [ ] #7274

@frozenbugs @peizhou001 @Rhett-Ying any operation I am missing above to enable full GraphBolt CUDA support?

**Comment by mfbalin** [comment]
@frozenbugs can we keep this issue as a tracker of the overall planned work for GraphBolt according to its design proposal? I plan to close it when the major proposed changes are done.

**Comment by mfbalin** [comment]
As you can see, there are unfinished tasks.
