### ISSUE TITLE
[Roadmap] Model Zoo for Chemistry

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#762]
We are planning to release a model zoo by the end of August and we use this issue to track our progress, PRs and other related staff.

Any related discussions and feedback are appreciated.

# Datasets
- [x] Tox21 (#753 @mufeili , #760 @VoVAllen )
- [x] Alchemy (#779 @geekinglcq )
    - Note that the current dataset implementation depends on PyTorch and we need to make it framework-agnostic.

# Models
## Property Prediction
- [x] [GCN on Tox21](https://arxiv.org/abs/1703.00564) (#753 @mufeili , #766 @VoVAllen )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
- [x] [GAT](https://arxiv.org/abs/1710.10903) (#793 @mufeili , under review)
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
- [x] [MGCN](https://arxiv.org/abs/1906.11081) (Early example in #726 @geekinglcq, refactored in #779 )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
- [x] [SchNet](https://arxiv.org/abs/1706.08566) (Early example in #726 @geekinglcq, refactored in #779 )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
- [x] [MPNN](https://arxiv.org/abs/1704.01212) (#779 @geekinglcq )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
## Generative Models
- [x] [DGMG](https://arxiv.org/abs/1803.03324) (#783 @mufeili )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation
- [x] [JTNN](https://arxiv.org/abs/1802.04364) (#790 @VoVAllen )
    - [x] Code
    - [x] Pre-trained models
    - [x] README/documentation

# Discussions & Issues

We are likely not going to draw a conclusion for several issues here, and they might be rather considered as notes for future actions.

## Breaking Pre-trained Models

A slight reorg of model architectures can easily break the pre-trained models. Since examples are not part of the library, this makes updating pre-trained models extremely difficult.

## Entry point

What should be the entry point/homepage of the model zoo? It should be concise and also contain necessary information and hyperlinks. 

## Additional dependencies

Our model zoo requires several additional dependencies. Currently we are explicitly listing them in a README file. But it's still highly likely that users will miss it or users need to manually install too many dependencies. Ideally it should only take users one action to install all the dependencies.

## The Use of Jupyter Notebook

Jupyter notebooks allow interactive usage examples and are preferred by some users for getting started. Nevertheless, it's very difficult to review jupyter notebooks.

## Compatibility with other libraries
There have been several efforts in bringing deep learning to chemistry. For example, [GuacaMol](https://github.com/BenevolentAI/guacamol) and [MOSES](https://github.com/molecularsets/moses) are two benchmarks for generative models and provide useful datasets and evaluation methods. It follows whether we should base our models upon them and whether our code should be compatible with their libraries.

## Stand alone or not?
Another question is whether the model zoo should be treated as a stand alone module like torchvision or just part of dgl along with some scripts. 

### Stand alone
**Pros**
- Allow DGL to focus on pure graph side and avoid becoming heavy with more applications
- Make application specific code more manageable

### Part of DGL
**Pros**
- No need to perform additional installation
- Likely to yield less overlapping with other libraries

## README and Tutorials
Due to the limited time, we will not be able to release tutorials simultaneously, nevertheless we should try to maintain good README which should include information like:
- Usage
- Concise and clear introduction about dataset, task and modeling
- Performance numbers
- ...

## Issues for Generative Models
The generative models can take days and even weeks for training and they are more difficult to be fairly evaluated. They also tend to be highly complex and likely more sensitive. These add several challenges comparing to property prediction models:
- More difficulties to match performance numbers
- Less reusable decoders
- Small modifications can break pre-trained models and even much worsen the performance.
