### ISSUE TITLE
[Roadmap] v0.5 release plan

### ISSUE THREAD

**Issue by jermainewang** [dmlc/dgl#930]
v0.5 Release
===
[Enhancement] Distributed GNN training
---
- [ ] Enable distributed computation for all core sampling/randomwalk APIs
- [ ] Distributed graph store design and implementation
- [x] Graph partition support. (#1308 )
- [ ] Support data stored on distributed filesystems (HDFS, S3, etc.)

[Enhancement] Core API refactor
---
- [ ] Support mutation for heterograph and deprecate adjacency list based data structure (RFC: #1118 )
- [ ] Explicit device and index type, support int32 graph (RFC: #1120 )
- [ ] Merge DGLGraph and DGLHeteroGraph
- [ ] Allow configuring the internal data structure of DGLGraph.
- [ ] More efficient CSR2COO, COO2CSR
- [ ] More efficient `dgl.reverse`
- [ ] More efficient `g.edge_ids` ([discussion](https://github.com/dmlc/dgl/pull/1440#discussion_r415328133))

[Doc] [Document improvement](https://github.com/dmlc/dgl/projects/8)
---
- [ ] Tutorials
  - [ ] Training GNNs with multi-GPU (PR: #1143 )
  - [ ] Step-by-step tutorial on constructing graphs from CSV data sources (Request: #1067).
- [ ] API references
  - [ ] Write an API overview section. More tasks will be added once the API overview section is out.
  - [ ] Data set API references and what are the available data sets. (Request: #1091).
  - [ ] C++ API reference. (Request: #1074 )
 - [ ] Distributed graph store API reference.

[Model] Recsys models
---
Similar to the DGL-KE and DGL-Chem packages, we'd like to organize popular models and datasets together for recommender system. We'd also like to take this chance to add CI and other relevant supports to DGL-KE and DGL-Chem.

[Feature] I/O
---
- [ ] Support loading graphs from graph database (e.g. Neo4j etc.)
- [ ] Support easy construction of DGL graphs from CSV data.

[Enhancement] NN modules
---
* Sequential pooling layer with new bipartite graph API.

Maybe later (after v0.5)
===
* [Enhancement] Point Cloud models (optional) #719 
  - [GAPNet](https://arxiv.org/pdf/1905.08705.pdf)
  - [GACNet](http://openaccess.thecvf.com/content_CVPR_2019/papers/Wang_Graph_Attention_Convolution_for_Point_Cloud_Semantic_Segmentation_CVPR_2019_paper.pdf)
  - [Superpoint Graph](https://arxiv.org/pdf/1711.09869.pdf)
  - [Deep GCNs](https://arxiv.org/pdf/1904.03751.pdf)
* GPU traversal. #1050
* Deep Numpy Support. #920
* ST-GCN (Pose) tutorial: https://arxiv.org/pdf/1801.07455.pdf
* ST-GCN (Traffic) (doesn't have to be a tutorial, although still useful to combine with the above): https://arxiv.org/pdf/1709.04875.pdf

v0.4.3 Release (Date: 03/31/2020)
---
Tracker: #1388 

v0.4.2 Release (Date: 01/23/2020)
---
- [x] Add utilities for featurization and graph construction (PR #928 ).
- [x] Add utilities for dataset splitting (PR #1117 )
- [x] Add AttentiveFP for property prediction (PR #955 )
- [x] Add PDBBind dataset and related featurization (PR #1117 )
- [x] Add data loading utilities (PR #1117 )
- [x] Add ACNN for protein-ligand binding affinity prediction (PR #1117 )
- [x] TF+DLPack solution (https://github.com/VoVAllen/tf-dlpack/issues/3)
- [x] Add tensorflow backend (PR: #978 )
- [x] CUDA 10.1 Support. (Request: #950, PR: #952)
- [x] Batching/unbatching DGLHeteroGraph (PR #1017 )
- [x] Support a S3 bucket in mainland China. (RFC: #1175 )

Feel free to reply and comment.

**Comment by futurely** [comment]
[Enhancement] Distributed training usability enhancement. Abstract generic distributed training tools from the examples and move them into the core. https://github.com/dmlc/dgl/issues/864

[Feature] Distributed graph store can be used not just by distributed KGE (knowledge graph embedding) training, but by arbitrary graph embedding training.  https://github.com/dmlc/dgl/issues/869

[Feature] Support TensorFlow https://github.com/dmlc/dgl/issues/422
[Feature] Support Keras API https://github.com/dmlc/dgl/issues/909

**Comment by VoVAllen** [comment]
Serialize HeteroGraph should also be included

**Comment by VoVAllen** [comment]
https://github.com/dmlc/dgl/issues/939
Adding this issue, to see whether we could do this with nodeflow.

**Comment by VoVAllen** [comment]
Also float16 support (Just for record, no intention to add it to 0.5)

**Comment by zheng-da** [comment]
> Serialize HeteroGraph should also be included

do you mean defining a format to store HeteroGraph in a file?

**Comment by VoVAllen** [comment]
@zheng-da Yes

**Comment by zheng-da** [comment]
We should add new datasets for RecSys and knowledge graphs:
RecSys:
* MovieLens
* BookCrossing
* Yelp
...

Knowledge Graphs:
* FB15k
* wn18
* Freebase
...

**Comment by jermainewang** [comment]
Since there are several dependency and building issues, I suggest we release a minor patch version v0.4.1 to fix them. It should at least include:
* Missing MXNet NN modules PR #890 .
* Upgrade pytorch dependency to v1.3.0 (Fix warning by ByteTensor) PR #954 
* Upgrade networkx dependency to v2.2 (Fix compatibility issue) PR #937 #949 
* Support CUDA 10.1. Issue #950 
* Bugfix #717 | #946

**Comment by zheng-da** [comment]
Accelerate graph query API on large graphs.

**Comment by MilkshakeForReal** [comment]
Recommender system is a very broad topic, I was wondering where we should get it started?

**Comment by zheng-da** [comment]
You are right. The initial release will include the following models:
* GCMC
* Star-GCN
* item-based recommendation using GraphSage/PinSage
* some models on knowledge graph aware recommendation

**Comment by VoVAllen** [comment]
DGL.subgraph do not support pickle (NotImplementedError: SubgraphIndex pickling is not supported yet.)

**Comment by VoVAllen** [comment]
Also pickling for DGLGraph is slow. This might be a bottleneck when sending multiple objects across multiprocessing

**Comment by mufeili** [comment]
Try removing atomic operations and guaranteeing deterministic behaviors, as mentioned in #908 .

**Comment by kingsaint** [comment]
R-GCN link prediction fails both on CPU (16G memory) and GPU (12G memory) for the FB15k-237 dataset. In both cases, it is trying to allocate additional memory during evaluation and failing. This needs to be resolved as R-GCN is used as a baseline for many experiments. Also, filtered metrics are not implemented. But I have a working code for filtered metrics. I can contribute to it.

**Comment by VoVAllen** [comment]
Thanks @kingsaint . We will try fix it.  More detail of this issue could be fount at https://github.com/dmlc/dgl/issues/997

**Comment by wenruij** [comment]
Is there a schedule for the new release?

**Comment by jermainewang** [comment]
We don't have an exact date yet. Nevertheless, many items are already done or under construction. Therefore, you could expect several minor releases before the full v0.5 because we'd like to deliver these features ASAP. We will update this roadmap to be a tracker so it is clearer what is happening.

**Comment by jermainewang** [comment]
Hi all, the team had some offline discussions and we decided to split the tasks into two releases so the progress is more tractable.  We plan to release a minor version v0.4.2 on **01/23/2020** includes important updates on documentation, tensorflow support, kernel optimization and application packages such as DGL-KE and DGL-chem. All the other features (and new requests) are pushed to v0.5, of which the exact date has not been fixed yet. @mufeili @zheng-da please update the TODO tasks in DGL-KE and DGL-Chem. Thanks.

**Comment by mufeili** [comment]
@jermainewang Done.

**Comment by wenruij** [comment]
@jermainewang Just want to confirm if the following models is included in  version v0.4.2:

- GCMC
- Star-GCN
- item-based recommendation using GraphSage/PinSage
- some models on knowledge graph aware recommendation

Looking forward to your wonderful work!

**Comment by jermainewang** [comment]
Hi everyone, we decided to publish a minor release v0.4.3 on **03/31/20** due to the increasing demand of nightly-build and for the first release of DGL-KE and DGL-LifeSci as standalone packages. Please refer to this [roadmap](https://github.com/dmlc/dgl/issues/1388) for more details.

**Comment by AlexMRuch** [comment]
Very excited to see some temporal graphs on the roadmap! I have experience with temporal modeling with RNNs and LSTMs but not with GNNs. Looking forward to learning more!

**Comment by classicsong** [comment]
> Very excited to see some temporal graphs on the roadmap! I have experience with temporal modeling with RNNs and LSTMs but not with GNNs. Looking forward to learning more!
> 
> Especially looking forward to something for temporal knowledge graphs, like RE-Net (https://arxiv.org/pdf/1904.05530.pdf), on `dgl`, that would be awesome. I know `pytorch_geometric` has an implementation: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/renet.py.

Here is an DGL implementatino of renet: https://github.com/changlinzhang/RENet

**Comment by BarclayII** [comment]
> > Very excited to see some temporal graphs on the roadmap! I have experience with temporal modeling with RNNs and LSTMs but not with GNNs. Looking forward to learning more!
> > Especially looking forward to something for temporal knowledge graphs, like RE-Net (https://arxiv.org/pdf/1904.05530.pdf), on `dgl`, that would be awesome. I know `pytorch_geometric` has an implementation: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/renet.py.
> 
> Here is an DGL implementatino of renet: https://github.com/changlinzhang/RENet

And also the official implementation of RE-Net uses DGL: https://github.com/INK-USC/RE-Net

**Comment by AlexMRuch** [comment]
> > Here is an DGL implementatino of renet: https://github.com/changlinzhang/RENet
> 
> And also the official implementation of RE-Net uses DGL: https://github.com/INK-USC/RE-Net

Ah, wow, I should have noticed that fact about the original repository. Thank you so much for the kind reminder!

**Comment by mufeili** [comment]
Just for a reminder, we will need to deprecate DGL-LifeSci in v0.5.

**Comment by wenruij** [comment]
Is DGL-RecSys coming soon? Is it possible to be released in July?

**Comment by lv2020** [comment]
When is it possible for DGL to support cuda 11? I just met so many problems about it. Thanks.

**Comment by VoVAllen** [comment]
@lv2020 Which framework are you using? Most frameworks are not released with CUDA 11 for now I think.

**Comment by lv2020** [comment]
> @lv2020 Which framework are you using? Most frameworks are not released with CUDA 11 for now I think.

I'm using pytorch. But the cuda version on my lab's server is 11, while I can't sudo. I also tried to build DGL from source but there were still somethings needed to sudo...

**Comment by VoVAllen** [comment]
@lv2020 I didn't see there's pytorch release with cuda 11. If you met permission problem, I would suggest using conda instead of pure python. `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` with `conda install dgl-cuda10.2 -c dglteam` should work

**Comment by lv2020** [comment]
> @lv2020 I didn't see there's pytorch release with cuda 11. If you met permission problem, I would suggest using conda instead of pure python. `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` with `conda install dgl-cuda10.2 -c dglteam` should work

In fact, the error is "OSError: libcublas.so.10: cannot open shared object file: No such file or directory". So I tried "conda install -c anaconda cudatoolkit=10.1" at first. But it doesn't work. And when I use nvidia-smi to check, I found the cuda version is 11.0. Then I tried to build the DGL from source. The main problem is that I need to install many packages which need sudo...

I also tried your command, it doesn't work either.

**Comment by VoVAllen** [comment]
Does conda work with pytorch on your machine?

**Comment by lv2020** [comment]
> Does conda work with pytorch on your machine?

I just reinstall pytorch and DGL with conda. It stiil doesn't work. And pytorch works with conda.

**Comment by lv2020** [comment]
> Does conda work with pytorch on your machine?

Thank you! I just solve the program by reinstalling pytorch and DGL with conda

**Comment by lv2020** [comment]
Thank you! I just solve the problem by reinstalling pytorch and DGL with conda

**Comment by AlexMRuch** [comment]
For what it's worth, @lv2020, it may make all of this easier for you to setup these libraries in their own conda environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands. Glad to hear you got things setup!

**Comment by hibayesian** [comment]
When will DGL support distributed training for very large-scale graphs(> billions nodes) which are stored on a distributed file system(e.g. HDFS)? I am also interested about whether there is a plan to integrate DGL with popular big data frameworks(e.g. Spark)?

**Comment by jermainewang** [comment]
DGL v0.5 has been released. See the release note here: https://github.com/dmlc/dgl/releases/tag/0.5.0 . We will keep patching any bugs and problems in the next few weeks. Will open a new roadmap thread for v0.6. Thanks everyone for the discussion here!
